// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AdicionandoumprodutoaocarrinhoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void adicionandoumprodutoaocarrinho() {
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.linkText("Blouse")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn-twitter"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn-facebook"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn-google-plus"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn-pinterest"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("#quantity_wanted_p > label")).click();
    driver.findElement(By.cssSelector("#quantity_wanted_p > label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#quantity_wanted_p > label"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    assertThat(driver.findElement(By.cssSelector("#quantity_wanted_p > label")).getText(), is("Quantity"));
    driver.findElement(By.cssSelector(".attribute_fieldset:nth-child(2) > .attribute_label")).click();
    driver.findElement(By.id("group_1")).click();
    driver.findElement(By.id("group_1")).click();
    driver.findElement(By.cssSelector(".attribute_fieldset:nth-child(2) > .attribute_label")).click();
    driver.findElement(By.cssSelector(".attribute_fieldset:nth-child(2) > .attribute_label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".attribute_fieldset:nth-child(2) > .attribute_label"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    assertThat(driver.findElement(By.cssSelector(".attribute_fieldset:nth-child(2) > .attribute_label")).getText(), is("Size "));
    driver.findElement(By.cssSelector(".attribute_fieldset:nth-child(3) > .attribute_label")).click();
    driver.findElement(By.cssSelector(".attribute_fieldset:nth-child(3) > .attribute_label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".attribute_fieldset:nth-child(3) > .attribute_label"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    assertThat(driver.findElement(By.cssSelector(".attribute_fieldset:nth-child(3) > .attribute_label")).getText(), is("Color "));
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    driver.findElement(By.cssSelector("h2:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("h2:nth-child(2)")).getText(), is("Product successfully added to your shopping cart"));
    driver.findElement(By.cssSelector(".continue > span")).click();
  }
}
