// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AdicionandoDoisprodutosaocarrinhoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void adicionandoDoisprodutosaocarrinho() {
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.linkText("Sign out")).click();
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("thiagoc.costaleal@gmail.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("55763ty15kb");
    driver.findElement(By.cssSelector("#SubmitLogin > span")).click();
    driver.findElement(By.cssSelector(".sfHover > .sf-with-ul")).click();
    driver.findElement(By.cssSelector(".hovered .product-name")).click();
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    driver.findElement(By.cssSelector(".continue > span")).click();
    driver.findElement(By.cssSelector(".sfHover > .sf-with-ul")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) > .subcategory-image .replace-2x")).click();
    driver.findElement(By.cssSelector(".right-block .product-name")).click();
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    driver.findElement(By.cssSelector(".layer_cart_cart > h2")).click();
    assertThat(driver.findElement(By.cssSelector(".ajax_cart_quantity:nth-child(1)")).getText(), is("2"));
    driver.findElement(By.cssSelector("h2:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("h2:nth-child(2)")).getText(), is("Product successfully added to your shopping cart"));
    driver.findElement(By.cssSelector(".cross")).click();
    driver.close();
  }
}
